# ==========================================
# 1. CONEXION A BASE DE DATOS
# ==========================================
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/flavis_db?serverTimezone=UTC&useSSL=false}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# 2. JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================================
# 3. SEGURIDAD JWT
# ==========================================
jwt.secret=${JWT_SECRET:4f61766973436f6f6b69657332303236536563757265546f6b656e58595a313233214023}

# ==========================================
# 4. CREDENCIALES DE ADMINISTRADORES
# ==========================================
flavis.admin1.email=${ADMIN1_EMAIL}
flavis.admin1.password=${ADMIN1_PASS}
flavis.admin2.email=${ADMIN2_EMAIL}
flavis.admin2.password=${ADMIN2_PASS}

# ==========================================
# 5. CONFIGURACION DE CLOUDINARY
# ==========================================
cloudinary.cloud_name=${CLOU_NAME}
cloudinary.api_key=${API_KEY}
cloudinary.api_secret=${API_SECRET}

# ==========================================
# 6. CONFIGURACIONES GENERALES
# ==========================================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Lima

# Tamaño máximo de archivos
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB